export {default as Footer} from './footer/Footer';
export {default as Header} from './header/Header';
export {default as Home} from './home/Home';
export {default as FAQ} from './faq/FAQ';
export {default as Team} from './team/Team';
export {default as EuReCa3} from './eureca3/EuReCa3';
export {default as Pub} from './pub/Pub';
export {default as Contacts} from './contacts/Contacts';
export {default as Posts} from './posts/Posts';
